// Edition-specific text and behaviour. This file is the internal edition and
// is what the source tree runs. `node scripts/build.mjs --client` ships
// js/edition.client.js under this name instead, so nothing in this file
// reaches the client build. Keep the two files' exports in step
// (tests/edition.test.mjs checks they match).

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

export const CLIENT = false;

export const FOOTER = 'Model year 2027, 15-minute intervals, naive local time. Rates from the Con Edison P.S.C. No. 10 tariff. Illustrative tool; verify against the filed rate book before customer use.';

// ---------------------------------------------------------------- diagnostics
export const logError = (e) => console.error(e);
export const logWarn = (...args) => console.warn(...args);
export const loadFailedHtml = (e) => `<p class="bad">Could not load the data files: ${esc(e.message)}</p><p class="note">Serve this folder over HTTP (for example <code>python3 -m http.server 8080</code>) and open it from there; file:// blocks fetch.</p>`;
export const errorHtml = (e) => `<p class="bad">${esc(e.message)}</p>`;
export const railErrorHtml = (e) => `<div class="card warn"><p class="flag">${esc(e.message)}</p></div>`;
export const runFailedHtml = (e) => `<p class="bad">Run failed: ${esc(e.message)}</p><p class="note">If this page was opened straight from the file system, serve it over HTTP (for example <code>python3 -m http.server</code>) so the WebAssembly solver can load.</p>`;
export const SOLVING = 'Building the year-long LP (about 140,000 variables) and solving with HiGHS. 5 to 20 seconds.';
export const solvedIn = (ms) => ` Solved in ${(ms / 1000).toFixed(1)} s.`;

// ---------------------------------------------------------------- provenance (HTML)
export const rateProvenance = (t) => ` Schedules compiled from book vintage <code>${esc(t.book_vintage)}</code> (candidate; cell-level lineage in the data file).`;
export const rateProvenanceClause = (t) => `; book vintage ${esc(t.book_vintage)} (candidate)`;
export const UNLISTED_STATEMENTS = 'Other statements (CES delivery surcharge, DLM surcharge, EV make-ready, arrears recovery) are not compiled: add them to the per-kWh figure if you want them.';
export const MSC_BLURB = 'Observed billed MSC from the corpus dataset (12 months to Aug 2026) plus the MSC capacity charge on the monthly maximum.';
export const PRESET_NOTE = 'Synthetic profiles generated by scripts/make_profiles.mjs: evening-peaking residential redistribution load with a temperature-driven cooling (and, for the heat-pump case, heating) component.';

// ---------------------------------------------------------------- engine text (plain; the UI escapes it)
export const mscProvenance = (msc) => `, dataset vintage ${msc.vintage}`;
export const lbmpSource = (lbmp) => `${lbmp.source}, ${lbmp.source_span.join(' to ')}`;
export const aggregatorNote = (id, pledge, minKw) => `${id}: the ${pledge} kW pledge counts toward an Aggregator's ${minKw} kW minimum per network (leaf 268).`;
export const PLEDGE_MISSING = 'Enter the pledged load relief (kW). It is a platform input and is never optimised.';
